trigger:
  branches:
    include:
      - main

parameters:
  - name: cold_run
    displayName: Cold run
    type: boolean
    default: false
  - name: environment
    displayName: Environment
    type: string
    default: qa
    values:
      - qa
      - prod

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate
    jobs:
      - job: Lint
        condition: false
        steps:
          - template: tasks/cli.yml
            parameters:
              environment: ${{ parameters.environment }}
              module: proenabler-ui
              task: lint

  - stage: Provision
    jobs:
      - job: StaticWebApp
        condition: false
        # condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
        steps:
          - template: tasks/cli.yml
            parameters:
              environment: ${{ parameters.environment }}
              module: proenabler-ui
              task: provision

  - stage: Deploy
    jobs:
      - job: StaticWebApp
        condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
        variables:
          - group: proenabler-ui-${{ parameters.environment }}
        steps:
          - checkout: self
            submodules: true
          - task: AzureStaticWebApp@0
            displayName: Static Web App
            inputs:
              verbose: true
              workingDirectory: 'src'
              app_location: '/'
              api_location: ''
              output_location: ''
              azure_static_web_apps_api_token: '$(DEPLOYMENT_TOKEN)'
          - publish: $(System.DefaultWorkingDirectory)/src/.next
            condition: always()
            artifact: .next
