parameters:
  - name: environment
  - name: module
  - name: task

steps:
  - pwsh: |
      Write-Host '##vso[task.setvariable variable=YARN_CACHE_FOLDER]$(Agent.TempDirectory)'
      Write-Host '##vso[task.setvariable variable=TMP]$(Agent.TempDirectory)'
      Write-Host '##vso[task.setvariable variable=TEMP]$(Agent.TempDirectory)'
      Write-Host '##vso[task.setvariable variable=TMPDIR]$(Agent.TempDirectory)'
      chown -R $(whoami) .
    displayName: init cli

  - task: AzureCLI@2
    displayName: amban ${{ parameters.module }} ${{ parameters.task }} ${{ parameters.ENVIRONMENT }}
    inputs:
      azureSubscription: "Amban - Clients(4a8b6bf8-1474-497c-95c8-094df7016840)"
      scriptType: "pscore"
      scriptLocation: "inlineScript"
      inlineScript: ./.build.ps1 ${{ parameters.module }} ${{ parameters.task }} ${{ parameters.ENVIRONMENT }}
